# Dockerfile

FROM openjdk:8-slim

MAINTAINER me@nalbam.com

ENV HOME /root

ARG VERSION=3.19
ARG AGENT_WORKDIR=${HOME}/agent

RUN apt-get update && \
    apt-get install -y curl docker

COPY jenkins-slave /usr/local/bin/jenkins-slave

RUN curl --create-dirs -sSLo /usr/share/jenkins/slave.jar \
    https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${VERSION}/remoting-${VERSION}.jar && \
    chmod 755 /usr/share/jenkins && \
    chmod 644 /usr/share/jenkins/slave.jar && \
    chmod 755 /usr/local/bin/jenkins-slave

ENV AGENT_WORKDIR=${AGENT_WORKDIR}

WORKDIR ${HOME}

ENTRYPOINT ["jenkins-slave"]
