# Dockerfile

FROM openjdk:8-jdk-alpine

MAINTAINER me@nalbam.com

ENV USER jenkins
ENV HOME /home/${USER}

ARG VERSION=3.19
ARG AGENT_WORKDIR=${HOME}/agent

RUN apt-get update && \
    apt-get install -y curl bash git docker && \
    addgroup -S -g 10000 ${USER} && \
    adduser -S -u 10000 -h $${HOME} -G ${USER} ${USER}

RUN curl --create-dirs -sSLo /usr/share/jenkins/slave.jar \
    https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${VERSION}/remoting-${VERSION}.jar && \
    chmod 755 /usr/share/jenkins && \
    chmod 644 /usr/share/jenkins/slave.jar

COPY jenkins-slave /usr/local/bin/jenkins-slave

USER ${USER}

ENV AGENT_WORKDIR=${AGENT_WORKDIR}

RUN mkdir -p ${HOME}/.jenkins && \
    mkdir -p ${HOME}/agent

VOLUME ${HOME}/.jenkins
VOLUME ${HOME}/agent

WORKDIR ${HOME}

ENTRYPOINT ["jenkins-slave"]
